# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-26 20:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholariumProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('stufe', models.IntegerField(choices=[(0, 'Interessent'), (1, 'Gast'), (2, 'Teilnehmer'), (3, 'Scholar'), (4, 'Partner'), (5, 'Beirat'), (6, 'Patron')], default=0)),
                ('anrede', models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau')], default='Herr', max_length=4, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('firma', models.CharField(blank=True, max_length=30, null=True)),
                ('strasse', models.CharField(blank=True, max_length=30, null=True)),
                ('plz', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('ort', models.CharField(blank=True, max_length=30, null=True)),
                ('land', models.CharField(blank=True, max_length=30, null=True)),
                ('guthaben', models.SmallIntegerField(default=0)),
                ('titel', models.CharField(blank=True, max_length=30, null=True)),
                ('anredename', models.CharField(blank=True, max_length=30, null=True)),
                ('letzte_zahlung', models.DateField(blank=True, null=True)),
                ('datum_ablauf', models.DateField(blank=True, null=True)),
                ('alt_id', models.SmallIntegerField(default=0, editable=False)),
                ('alt_notiz', models.CharField(default='', editable=False, max_length=255, null=True)),
                ('alt_scholien', models.SmallIntegerField(default=0, editable=False, null=True)),
                ('alt_mahnstufe', models.SmallIntegerField(default=0, editable=False, null=True)),
                ('alt_auslaufend', models.SmallIntegerField(default=0, editable=False, null=True)),
                ('alt_gave_credits', models.SmallIntegerField(default=0, editable=False, null=True)),
                ('alt_registration_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Nutzerprofil',
                'verbose_name_plural': 'Nutzerprofile',
            },
        ),
    ]
