# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-06 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholariumprofile',
            name='alt_auslaufend',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='alt_gave_credits',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='alt_id',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='alt_mahnstufe',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='alt_notiz',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='alt_registration_ip',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='alt_scholien',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='anredename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='datum_ablauf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='letzte_zahlung',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholariumprofile',
            name='titel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scholariumprofile',
            name='guthaben',
            field=models.SmallIntegerField(default=0),
        ),
    ]
