# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-04 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0002_scholariumprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hauptpunkt',
            options={'verbose_name_plural': 'Menü - Hauptpunkte'},
        ),
        migrations.AlterModelOptions(
            name='scholariumprofile',
            options={'verbose_name': 'Nutzerprofil', 'verbose_name_plural': 'Nutzerprofile'},
        ),
        migrations.AlterModelOptions(
            name='unterpunkt',
            options={'verbose_name_plural': 'Menü - Unterpunkte'},
        ),
    ]
