# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-07 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0002_auto_20170306_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_registration_ip',
            field=models.GenericIPAddressField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='scholariumprofile',
            name='anrede',
            field=models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau')], default='Herr', max_length=4, null=True),
        ),
    ]
