# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-07 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0003_auto_20170307_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_auslaufend',
            field=models.SmallIntegerField(default=0, editable=False, null=True),
        ),
    ]
