# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0003_auto_20171027_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_auslaufend',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
