# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0004_auto_20171211_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_auslaufend',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='auslaufend'),
        ),
    ]
