# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0004_auto_20170307_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_gave_credits',
            field=models.SmallIntegerField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_mahnstufe',
            field=models.SmallIntegerField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_scholien',
            field=models.SmallIntegerField(default=0, editable=False, null=True),
        ),
    ]
