# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0005_auto_20170429_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitwirkende',
            options={'ordering': ('level', 'start', 'id_old'), 'verbose_name': 'Mitwirkender', 'verbose_name_plural': 'Mitwirkende'},
        ),
        migrations.AddField(
            model_name='mitwirkende',
            name='id_old',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mitwirkende',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rektor'), (2, 'Gründer'), (3, 'Mitarbeiter'), (4, 'Mentoren')], default=1),
        ),
    ]
