# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0005_auto_20170307_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='alt_notiz',
            field=models.CharField(default='', editable=False, max_length=255, null=True),
        ),
    ]
