# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0005_auto_20170429_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitwirkende',
            name='id_old',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
