# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0006_auto_20170510_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitwirkende',
            options={'ordering': ('level', 'start', 'alt_id'), 'verbose_name': 'Mitwirkender', 'verbose_name_plural': 'Mitwirkende'},
        ),
        migrations.RenameField(
            model_name='mitwirkende',
            old_name='id_old',
            new_name='alt_id',
        ),
        migrations.AlterField(
            model_name='mitwirkende',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
