# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0006_auto_20170307_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitwirkende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('text_de', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.SmallIntegerField()),
                ('start', models.DateField(blank=True, null=True)),
                ('ende', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mitwirkender',
                'verbose_name_plural': 'Mitwirkende',
            },
        ),
    ]
