# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0006_mitwirkende_id_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitwirkende',
            name='id_old',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
