# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0006_auto_20180124_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
