# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-18 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userena', '0002_auto_20170319_0908'),
        ('Grundgeruest', '0006_auto_20170307_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeinUserenaSignup',
            fields=[
                ('userenasignup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userena.UserenaSignup')),
            ],
            bases=('userena.userenasignup',),
        ),
    ]
