# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0007_auto_20180323_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stufe',
            fields=[
                ('bezeichnung', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('betrag', models.IntegerField()),
                ('inhalt', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Stufen',
            },
        ),
        migrations.CreateModel(
            name='Unterstuetzung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.date(2018, 3, 27))),
                ('zahlungsmethode', models.CharField(blank=True, max_length=100)),
                ('stufe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Grundgeruest.Stufe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grundgeruest.ScholariumProfile')),
            ],
            options={
                'verbose_name_plural': 'Unterstuetzungen',
            },
        ),
    ]
