# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-14 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0007_mitwirkende'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitwirkende',
            name='bezeichnung',
        ),
        migrations.RemoveField(
            model_name='mitwirkende',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mitwirkende',
            name='zeit_erstellt',
        ),
    ]
