# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0007_auto_20170510_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitwirkende',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rektor'), (2, 'Gründer'), (3, 'Mitarbeiter'), (4, 'Mentor')], default=1),
        ),
    ]
