# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0008_auto_20170505_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitwirkende',
            name='id_old',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True),
        ),
    ]
