# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0010_auto_20171023_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganzesmenue',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hauptpunkt',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unterpunkt',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
    ]
