# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-06 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0010_auto_20180327_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unterstuetzung',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
