# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0011_auto_20180406_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterstuetzung',
            name='ueberprueft',
            field=models.BooleanField(default=False),
        ),
    ]
