# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0012_remove_mitwirkende_id_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitwirkende',
            name='id_old',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
