# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0012_unterstuetzung_ueberprueft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholariumprofile',
            name='alt_auslaufend',
        ),
        migrations.AddField(
            model_name='unterstuetzung',
            name='notiz',
            field=models.TextField(blank=True),
        ),
    ]
