# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0013_auto_20180416_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unterstuetzung',
            name='notiz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unterstuetzung',
            name='zahlungsmethode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
