# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0015_unterstuetzung_zahlung_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholariumprofile',
            name='datum_ablauf',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='scholariumprofile',
            name='letzte_zahlung',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='scholariumprofile',
            name='stufe',
            field=models.IntegerField(choices=[(0, 'Interessent'), (1, 'Gast'), (2, 'Teilnehmer'), (3, 'Scholar'), (4, 'Partner'), (5, 'Beirat'), (6, 'Patron')], default=0, editable=False),
        ),
    ]
