# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-08 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0015_auto_20170508_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuraktive',
            name='mitwirkende_ptr',
        ),
        migrations.DeleteModel(
            name='NurAktive',
        ),
    ]
