# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0016_auto_20170508_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurAktive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
