# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-08 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0017_nuraktive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NurAktive',
        ),
    ]
