# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-26 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Veranstaltungen', '__first__'),
        ('Grundgeruest', '0003_mitwirkende'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kauf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.SmallIntegerField(blank=True, default=1)),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('guthaben_davor', models.SmallIntegerField(editable=False)),
                ('nutzer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grundgeruest.ScholariumProfile')),
            ],
            options={
                'verbose_name_plural': 'Käufe',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('preis', models.SmallIntegerField(blank=True, null=True)),
                ('art_produkt', models.CharField(choices=[('Teilnahme', 'Teilnahme'), ('Livestream', 'Livestream'), ('Videoaufzeichnung', 'Videoaufzeichnung'), ('Audioaufzeichnung', 'Audioaufzeichnung')], default='', max_length=25)),
                ('kaeufe', models.ManyToManyField(editable=False, through='Produkte.Kauf', to='Grundgeruest.ScholariumProfile')),
                ('zu_medium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Veranstaltungen.Medium')),
                ('zu_studiumdings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Veranstaltungen.Studiumdings')),
                ('zu_veranstaltung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Veranstaltungen.Veranstaltung')),
            ],
            options={
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.CreateModel(
            name='Spendenstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('spendenbeitrag', models.SmallIntegerField()),
                ('beschreibung', models.TextField()),
                ('gegenwert1', models.TextField(blank=True, null=True)),
                ('gegenwert2', models.TextField(blank=True, null=True)),
                ('gegenwert3', models.TextField(blank=True, null=True)),
                ('gegenwert4', models.TextField(blank=True, null=True)),
                ('gegenwert5', models.TextField(blank=True, null=True)),
                ('gegenwert6', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Spendenstufen',
            },
        ),
        migrations.AddField(
            model_name='kauf',
            name='produkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produkte.Produkt'),
        ),
    ]
