# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grundgeruest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kauf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt_pk', models.CharField(max_length=40)),
                ('menge', models.SmallIntegerField(blank=True, default=1)),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('kommentar', models.CharField(blank=True, max_length=255)),
                ('guthaben_davor', models.SmallIntegerField(editable=False, null=True)),
                ('nutzer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grundgeruest.ScholariumProfile')),
            ],
            options={
                'verbose_name_plural': 'Käufe',
            },
        ),
        migrations.CreateModel(
            name='Spendenstufe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('spendenbeitrag', models.SmallIntegerField()),
                ('beschreibung', models.TextField()),
                ('gegenwert1', models.TextField(blank=True, null=True)),
                ('gegenwert2', models.TextField(blank=True, null=True)),
                ('gegenwert3', models.TextField(blank=True, null=True)),
                ('gegenwert4', models.TextField(blank=True, null=True)),
                ('gegenwert5', models.TextField(blank=True, null=True)),
                ('gegenwert6', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Spendenstufen',
            },
        ),
    ]
