# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-10 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0002_spendenstufen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendenstufen',
            options={'verbose_name_plural': 'Unterstützen - Spendenstufen'},
        ),
    ]
