# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-08 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0003_auto_20170504_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kauf',
            name='produkt_art',
        ),
        migrations.RemoveField(
            model_name='kauf',
            name='produkt_id',
        ),
        migrations.RemoveField(
            model_name='kauf',
            name='produkt_model',
        ),
        migrations.AddField(
            model_name='kauf',
            name='produkt_pk',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
