# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-15 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0003_auto_20170310_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spendenstufen',
            new_name='Spendenstufe',
        ),
        migrations.AlterModelOptions(
            name='spendenstufe',
            options={'verbose_name_plural': 'Spendenstufen'},
        ),
    ]
