# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0003_auto_20171027_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendenstufe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
