# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0007_auto_20170421_0715'),
        ('Produkte', '0004_auto_20170315_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zu_studium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Veranstaltungen.Studiumdings'),
        ),
    ]
