# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-08 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0004_auto_20170508_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='zu_medium',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='zu_studiumdings',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='zu_veranstaltung',
        ),
        migrations.DeleteModel(
            name='Produkt',
        ),
    ]
