# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-21 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0005_auto_20170508_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kauf',
            name='guthaben_davor',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
    ]
