# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-21 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0005_produkt_zu_studium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='zu_studium',
            new_name='zu_studiumdings',
        ),
    ]
