# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0006_auto_20170921_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='kauf',
            name='kommentar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
