# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0007_kauf_kommentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kauf',
            name='produkt_pk',
            field=models.CharField(max_length=40),
        ),
    ]
