# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0008_auto_20170921_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendenstufe',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
    ]
