# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('inhalt', models.TextField()),
                ('inhalt_nur_fuer_angemeldet', models.TextField(blank=True, null=True)),
                ('datum_publizieren', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artikel',
                'verbose_name': 'Artikel',
                'ordering': ['-datum_publizieren'],
            },
        ),
        migrations.CreateModel(
            name='Buechlein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='scholienbuechlein')),
                ('epub', models.FileField(blank=True, null=True, upload_to='scholienbuechlein')),
                ('mobi', models.FileField(blank=True, null=True, upload_to='scholienbuechlein')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='scholienbuechlein')),
                ('beschreibung', models.TextField(blank=True, max_length=2000, null=True)),
                ('alte_nr', models.SmallIntegerField(editable=False, null=True)),
                ('preis_druck', models.SmallIntegerField(blank=True, null=True)),
                ('anzahl_druck', models.SmallIntegerField(blank=True, default=0)),
                ('preis_pdf', models.SmallIntegerField(blank=True, null=True)),
                ('ob_pdf', models.BooleanField(default=0)),
                ('preis_epub', models.SmallIntegerField(blank=True, null=True)),
                ('ob_epub', models.BooleanField(default=0)),
                ('preis_mobi', models.SmallIntegerField(blank=True, null=True)),
                ('ob_mobi', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Büchlein',
                'verbose_name': 'Büchlein',
                'ordering': ['-alte_nr'],
            },
        ),
    ]
