# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buechlein',
            name='typ',
        ),
        migrations.AddField(
            model_name='buechlein',
            name='bild',
            field=models.FileField(null=True, upload_to='scholienbuechlein'),
        ),
        migrations.AlterField(
            model_name='buechlein',
            name='pdf',
            field=models.FileField(null=True, upload_to='scholienbuechlein'),
        ),
    ]
