# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-09 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0002_buechlein_arten_dicts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buechlein',
            name='arten_dicts',
        ),
        migrations.AddField(
            model_name='buechlein',
            name='anzahl_druck',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='anzahl_epub',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='anzahl_mobi',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='anzahl_pdf',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='preis_druck',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='preis_epub',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='preis_mobi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='preis_pdf',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
