# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0003_auto_20170510_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='buechlein',
            name='alte_nr',
            field=models.SmallIntegerField(editable=False, null=True),
        ),
    ]
