# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0003_auto_20171027_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='buechlein',
            name='admin_kaeufe',
            field=models.TextField(default=''),
        ),
    ]
