# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0004_buechlein_admin_kaeufe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buechlein',
            name='admin_kaeufe',
            field=models.TextField(blank=True, default=''),
        ),
    ]
