# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0005_auto_20170510_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buechlein',
            name='anzahl_epub',
        ),
        migrations.RemoveField(
            model_name='buechlein',
            name='anzahl_mobi',
        ),
        migrations.RemoveField(
            model_name='buechlein',
            name='anzahl_pdf',
        ),
        migrations.AddField(
            model_name='buechlein',
            name='ob_epub',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='ob_mobi',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='ob_pdf',
            field=models.BooleanField(default=0),
        ),
    ]
