# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0006_artikel_prioritaet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownArtikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('prioritaet', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Markdown Artikel',
                'verbose_name_plural': 'Markdown Artikel',
                'ordering': ['-zeit_erstellt'],
            },
        ),
    ]
