# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-31 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0006_auto_20170531_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='buechlein',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to='scholienbuechlein'),
        ),
        migrations.AddField(
            model_name='buechlein',
            name='mobi',
            field=models.FileField(blank=True, null=True, upload_to='scholienbuechlein'),
        ),
        migrations.AlterField(
            model_name='buechlein',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='scholienbuechlein'),
        ),
        migrations.AlterField(
            model_name='buechlein',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='scholienbuechlein'),
        ),
    ]
