# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0008_markdownartikel_artikel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownartikel',
            name='artikel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Scholien.Artikel'),
        ),
    ]
