# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0009_auto_20171211_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='literatur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
