# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholien', '0010_artikel_literatur'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='inhalt2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
