# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studiumdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('beschreibung', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Studiendinger',
            },
        ),
    ]
