# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
