# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0003_veranstaltung_preis'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='arten_dicts',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studiumdings',
            name='arten_dicts',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='arten_dicts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
