# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0003_auto_20170306_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiumdings',
            name='beschreibung',
            field=models.TextField(),
        ),
    ]
