# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0004_auto_20171104_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiumdings',
            name='admin_kaeufe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='admin_kaeufe',
            field=models.TextField(blank=True, default=''),
        ),
    ]
