# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-21 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0004_auto_20170306_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiumdings',
            old_name='beschreibung',
            new_name='beschreibung2',
        ),
    ]
