# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-09 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0004_auto_20170508_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='datei',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
