# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-21 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0005_auto_20170421_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiumdings',
            name='beschreibung1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
