# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-21 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0006_studiumdings_beschreibung1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiumdings',
            name='beschreibung1',
            field=models.TextField(),
        ),
    ]
