# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0008_auto_20170511_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veranstaltung',
            name='anzahl_aufzeichnung',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='anzahl_livestream',
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='ob_aufzeichnung',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='ob_livestream',
            field=models.BooleanField(default=0),
        ),
    ]
