# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-11 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0009_auto_20170531_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='beschreibung2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
