# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-29 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0010_veranstaltung_beschreibung2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artderveranstaltung',
            old_name='preis_praesenz',
            new_name='preis_teilnahme',
        ),
    ]
