# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0011_auto_20170929_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='beschreibung2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
