# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0012_auto_20171003_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='ob_chat_anzeigen',
            field=models.BooleanField(default=False),
        ),
    ]
