# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0013_veranstaltung_ob_chat_anzeigen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiumdings',
            options={'ordering': ['reihenfolge'], 'verbose_name': 'Studienprogramm', 'verbose_name_plural': 'Studienprogramme'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AddField(
            model_name='studiumdings',
            name='ob_buchung',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='studiumdings',
            name='preis_buchung',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
