# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0015_auto_20171025_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artderveranstaltung',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studiumdings',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
    ]
