# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0016_auto_20171025_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiumdings',
            name='anzahl_teilnahme',
        ),
        migrations.RemoveField(
            model_name='studiumdings',
            name='preis_teilnahme',
        ),
    ]
