# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-16 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notizzettel',
                'verbose_name': 'Notizzettel',
            },
        ),
        migrations.CreateModel(
            name='Zeile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('autor_name', models.CharField(blank=True, max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notizen.Liste')),
            ],
            options={
                'verbose_name_plural': 'Notizzeilen',
                'ordering': ['-zeit_erstellt'],
                'verbose_name': 'Notizzeile',
            },
        ),
    ]
