# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veranstaltungen', '0012_auto_20171003_1603'),
        ('Notizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Veranstaltungen.Veranstaltung'),
            preserve_default=False,
        ),
    ]
