# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notizen', '0003_remove_zeile_autor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Veranstaltungen.Veranstaltung'),
        ),
    ]
