# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-17 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notizen', '0004_auto_20171017_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeile',
            name='zeit_geaendert',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 10, 17, 13, 22, 45, 673281)),
            preserve_default=False,
        ),
    ]
