# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notizen', '0005_zeile_zeit_geaendert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='bezeichnung',
        ),
        migrations.RemoveField(
            model_name='zeile',
            name='bezeichnung',
        ),
    ]
