# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-10 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='anzahl_kaufen',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='buch',
            name='anzahl_leihen',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='buch',
            name='preis_kaufen',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='preis_leihen',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
