# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-07 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0003_auto_20170602_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Altes_Buch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('autor_und_titel', models.CharField(blank=True, max_length=255, null=True)),
                ('preis_kaufen', models.SmallIntegerField(blank=True, null=True)),
                ('anzahl_kaufen', models.SmallIntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
