# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-01 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0004_altes_buch'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='anzahl_druck',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='buch',
            name='ob_epub',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='buch',
            name='ob_mobi',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='buch',
            name='ob_pdf',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='buch',
            name='preis_druck',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='preis_epub',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='preis_mobi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buch',
            name='preis_pdf',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
