# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0007_auto_20171003_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buch',
            options={'verbose_name': 'Buch', 'verbose_name_plural': 'Bücher'},
        ),
    ]
