# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0008_auto_20171025_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altes_buch',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='buch',
            name='bezeichnung',
            field=models.CharField(max_length=200),
        ),
    ]
